/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Controlador;
import Model.Actividad;
import Model.Usuario;
import static Utils.Utils.safeParseToString;
import static Utils.Utils.sqlDate;
import java.awt.CardLayout;
import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;
import static proyecto.Proyecto.Ctrl;

/**
 *
 * @author eadan
 */
public class MainView extends javax.swing.JFrame {

    Usuario current_user;
    Controlador Ctrl = Controlador.getInstance();
    javax.swing.JFrame parent;
    DefaultListModel actividadesListModel, avancesListModel;
    Actividad current_actividad;
    MainView(Login parent, Usuario current_user) {
        this.parent = parent;
        this.current_user = current_user;
        initComponents();
        txtPerfilUsuario.setText(current_user.getNombre());
        txtPerfilCorreo.setText(current_user.getCorreo());
        actividadesListModel=new DefaultListModel();
        avancesListModel=new DefaultListModel();
        lstActividades.setModel(actividadesListModel);
        lstActividadAvances.setModel(avancesListModel);
        fillActivitiesList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        paneActividadesBase = new javax.swing.JPanel();
        paneActividadesLista = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lstActividadActividades = new javax.swing.JScrollPane();
        lstActividades = new javax.swing.JList<>();
        paneActividadesActividad = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtActividadFechaCreacion = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtActividadFechaCompletado = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtActividadFechaInicio = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtActividadFechaFin = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtActividadNotas = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtActividadEtiquetas = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtActividadPadre = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtActividadId = new javax.swing.JLabel();
        txtActividadAvances = new javax.swing.JLabel();
        txtActividadNombre = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtActividadIdUsuario = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnActividadIrAtras = new javax.swing.JButton();
        btnActividadAgregarAvance = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstActividadAvances = new javax.swing.JList<>();
        jLabel21 = new javax.swing.JLabel();
        paneActividadesAgregarAvance = new javax.swing.JPanel();
        spnAvanceHoras = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAvanceDescripcion = new javax.swing.JTextArea();
        btnAgregarAvance = new javax.swing.JButton();
        cmbAvanceTipo = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        paneImportar = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtImportarPath = new javax.swing.JTextField();
        btnImportarSeleccionar = new javax.swing.JButton();
        btnImportarImportar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPerfilUsuario = new javax.swing.JTextField();
        txtPerfilCorreo = new javax.swing.JTextField();
        pwdPerfilContra1 = new javax.swing.JPasswordField();
        pwdPerfilContra2 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        paneActividadesBase.setLayout(new java.awt.CardLayout());

        jLabel1.setText("Actividades");

        jLabel7.setText("Haga click en una actividad para ver sus avances");

        lstActividades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstActividadesMouseClicked(evt);
            }
        });
        lstActividadActividades.setViewportView(lstActividades);

        javax.swing.GroupLayout paneActividadesListaLayout = new javax.swing.GroupLayout(paneActividadesLista);
        paneActividadesLista.setLayout(paneActividadesListaLayout);
        paneActividadesListaLayout.setHorizontalGroup(
            paneActividadesListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneActividadesListaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneActividadesListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneActividadesListaLayout.createSequentialGroup()
                        .addGroup(paneActividadesListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lstActividadActividades, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE))
                .addContainerGap())
        );
        paneActividadesListaLayout.setVerticalGroup(
            paneActividadesListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneActividadesListaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lstActividadActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneActividadesBase.add(paneActividadesLista, "lista");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Información"));

        jLabel13.setText("Id Usuario:");

        txtActividadFechaCreacion.setText("jLabel24");

        jLabel14.setText("Fecha Creación:");

        txtActividadFechaCompletado.setText("jLabel25");

        jLabel15.setText("Fecha Completado:");

        txtActividadFechaInicio.setText("jLabel26");

        jLabel16.setText("Fecha Inicio:");

        txtActividadFechaFin.setText("jLabel27");

        jLabel17.setText("Fecha Fin:");

        txtActividadNotas.setText("jLabel28");

        jLabel18.setText("Etiquetas:");

        txtActividadEtiquetas.setText("jLabel29");

        jLabel19.setText("Notas:");

        txtActividadPadre.setText("jLabel30");

        jLabel20.setText("Tarea padre:");

        jLabel31.setText("Avances:");

        txtActividadId.setText("jLabel21");

        txtActividadAvances.setText("jLabel32");

        txtActividadNombre.setText("jLabel22");

        jLabel11.setText("Identificador:");

        jLabel12.setText("Nombre:");

        txtActividadIdUsuario.setText("jLabel23");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtActividadId))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtActividadNombre))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtActividadFechaFin))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtActividadFechaInicio))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtActividadFechaCompletado))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtActividadFechaCreacion))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtActividadIdUsuario))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtActividadPadre))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtActividadEtiquetas))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtActividadNotas))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtActividadAvances)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtActividadId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtActividadNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtActividadIdUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(txtActividadFechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtActividadFechaCompletado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtActividadFechaInicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtActividadFechaFin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtActividadNotas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtActividadEtiquetas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtActividadPadre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txtActividadAvances))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        btnActividadIrAtras.setText("Ir atras");
        btnActividadIrAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActividadIrAtrasActionPerformed(evt);
            }
        });

        btnActividadAgregarAvance.setText("Agregar avance");
        btnActividadAgregarAvance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActividadAgregarAvanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnActividadIrAtras)
                    .addComponent(btnActividadAgregarAvance))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnActividadAgregarAvance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(btnActividadIrAtras)
                .addContainerGap())
        );

        lstActividadAvances.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstActividadAvances.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstActividadAvancesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstActividadAvances);

        jLabel21.setText("Lista de Avances");

        javax.swing.GroupLayout paneActividadesActividadLayout = new javax.swing.GroupLayout(paneActividadesActividad);
        paneActividadesActividad.setLayout(paneActividadesActividadLayout);
        paneActividadesActividadLayout.setHorizontalGroup(
            paneActividadesActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneActividadesActividadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneActividadesActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(paneActividadesActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneActividadesActividadLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel21)
                        .addContainerGap(224, Short.MAX_VALUE))
                    .addGroup(paneActividadesActividadLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
        );
        paneActividadesActividadLayout.setVerticalGroup(
            paneActividadesActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneActividadesActividadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneActividadesActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneActividadesActividadLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(paneActividadesActividadLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        paneActividadesBase.add(paneActividadesActividad, "actividad");

        jLabel22.setText("Agregar avance");

        jLabel23.setText("Horas dedicadas:");

        jLabel24.setText("Descripción:");

        txtAvanceDescripcion.setColumns(20);
        txtAvanceDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtAvanceDescripcion);

        btnAgregarAvance.setText("Agregar avance");
        btnAgregarAvance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAvanceActionPerformed(evt);
            }
        });

        cmbAvanceTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solución de error", "Actualización", "Finalización" }));

        jLabel25.setText("Tipo de avance:");

        jButton2.setText("Ir atras");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneActividadesAgregarAvanceLayout = new javax.swing.GroupLayout(paneActividadesAgregarAvance);
        paneActividadesAgregarAvance.setLayout(paneActividadesAgregarAvanceLayout);
        paneActividadesAgregarAvanceLayout.setHorizontalGroup(
            paneActividadesAgregarAvanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneActividadesAgregarAvanceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneActividadesAgregarAvanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneActividadesAgregarAvanceLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE))
                    .addGroup(paneActividadesAgregarAvanceLayout.createSequentialGroup()
                        .addGroup(paneActividadesAgregarAvanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addGroup(paneActividadesAgregarAvanceLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnAvanceHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paneActividadesAgregarAvanceLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbAvanceTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneActividadesAgregarAvanceLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(paneActividadesAgregarAvanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAgregarAvance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        paneActividadesAgregarAvanceLayout.setVerticalGroup(
            paneActividadesAgregarAvanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneActividadesAgregarAvanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneActividadesAgregarAvanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(spnAvanceHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneActividadesAgregarAvanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(cmbAvanceTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneActividadesAgregarAvanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarAvance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        paneActividadesBase.add(paneActividadesAgregarAvance, "agregarAvance");
        paneActividadesAgregarAvance.getAccessibleContext().setAccessibleName("");

        tabbedPane.addTab("Actividades", paneActividadesBase);

        jLabel8.setText("Importar proyecto");

        jLabel9.setText("Seleccione el JSON de Asana");

        jLabel10.setText("Archivo:");

        txtImportarPath.setEditable(false);

        btnImportarSeleccionar.setText("Seleccionar");
        btnImportarSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarSeleccionarActionPerformed(evt);
            }
        });

        btnImportarImportar.setText("Importar");
        btnImportarImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarImportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneImportarLayout = new javax.swing.GroupLayout(paneImportar);
        paneImportar.setLayout(paneImportarLayout);
        paneImportarLayout.setHorizontalGroup(
            paneImportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneImportarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneImportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addGroup(paneImportarLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtImportarPath, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paneImportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnImportarImportar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnImportarSeleccionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        paneImportarLayout.setVerticalGroup(
            paneImportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneImportarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneImportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtImportarPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImportarSeleccionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImportarImportar)
                .addContainerGap(359, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Importar", paneImportar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Exportar", jPanel1);

        jLabel2.setText("Editar perfil");

        jButton1.setText("Guardar cambios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Usuario:");

        jLabel4.setText("Correo electrónico:");

        jLabel5.setText("Contraseña: ");

        txtPerfilUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPerfilUsuarioActionPerformed(evt);
            }
        });

        txtPerfilCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPerfilCorreoActionPerformed(evt);
            }
        });

        jLabel6.setText("Confirmar contraseña:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pwdPerfilContra1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtPerfilCorreo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPerfilUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pwdPerfilContra2))
                        .addGap(0, 308, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPerfilUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPerfilCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pwdPerfilContra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwdPerfilContra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        tabbedPane.addTab("Perfil", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String pwd1 = String.valueOf(pwdPerfilContra1.getPassword()), pwd2 = String.valueOf(pwdPerfilContra2.getPassword());
        if (pwd1.compareTo(pwd2)!=0){
            JOptionPane.showMessageDialog(this,
                "Las contraseñas no coinciden.",
                "Error de validación",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        current_user.setNombre(txtPerfilUsuario.getText());
        current_user.setCorreo(txtPerfilCorreo.getText());
        current_user.setPassword(pwd1);
        
        Ctrl.ActualizarUsuario(current_user);
        JOptionPane.showMessageDialog(this,
                "Se han actualizado los datos del perfil exitosamente.",
                "Operación exitosa",
                JOptionPane.INFORMATION_MESSAGE);
            return;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPerfilUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPerfilUsuarioActionPerformed
       txtPerfilUsuario.setText("");
    }//GEN-LAST:event_txtPerfilUsuarioActionPerformed

    private void txtPerfilCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPerfilCorreoActionPerformed
        txtPerfilCorreo.setText("");
    }//GEN-LAST:event_txtPerfilCorreoActionPerformed

    private void btnImportarSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarSeleccionarActionPerformed
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        jfc.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JSON de Asana", "json", "txt");
        jfc.addChoosableFileFilter(filter);
        int returnValue = jfc.showOpenDialog(this);
        // int returnValue = jfc.showSaveDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
                File selectedFile = jfc.getSelectedFile();
                txtImportarPath.setText(selectedFile.getAbsolutePath());    
        }
    }//GEN-LAST:event_btnImportarSeleccionarActionPerformed

    private void btnImportarImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarImportarActionPerformed
        try{
            String path = txtImportarPath.getText();
            if (!path.endsWith(".json")&&!path.endsWith(".txt"))
                throw new Exception();
            Ctrl.ImportarArchivo(path);    
            JOptionPane.showMessageDialog(this,
            "Se ha importado los datos del proyecto exitosamente.",
            "Operación exitosa",
            JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,
            "Ha ocurrido un error al importar el proyecto.",
            "Error",
            JOptionPane.ERROR_MESSAGE);
        }           
    }//GEN-LAST:event_btnImportarImportarActionPerformed

    private void lstActividadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstActividadesMouseClicked
        JList list = (JList) evt.getSource();
        if(evt.getClickCount()>=2){
            int index=list.locationToIndex(evt.getPoint());
            
            current_actividad = (Actividad)actividadesListModel.get(index);
            txtActividadId.setText(current_actividad.getIdTarea());
            txtActividadNombre.setText(current_actividad.getNombreTarea());
            txtActividadIdUsuario.setText(current_actividad.getIdUsuario());
            txtActividadFechaCreacion.setText(safeParseToString(current_actividad.getFechaCreacion()));
            txtActividadFechaCompletado.setText(safeParseToString(current_actividad.getFechaCompletado()));
            txtActividadFechaInicio.setText(safeParseToString(current_actividad.getFechaInicio()));
            txtActividadFechaFin.setText(safeParseToString(current_actividad.getFechaFin()));
            txtActividadNotas.setText(current_actividad.getNota());
            txtActividadEtiquetas.setText(current_actividad.getEtiqueta());
            txtActividadPadre.setText(current_actividad.getTareaPadre());
            
            int items_agregados=fillAvancesList();
            txtActividadAvances.setText(String.valueOf(items_agregados));
            
            
            ((CardLayout)paneActividadesBase.getLayout()).show(paneActividadesBase, "actividad");
            
        }
    }//GEN-LAST:event_lstActividadesMouseClicked

    private void btnActividadIrAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActividadIrAtrasActionPerformed
        ((CardLayout)paneActividadesBase.getLayout()).show(paneActividadesBase, "lista");
    }//GEN-LAST:event_btnActividadIrAtrasActionPerformed

    private void btnActividadAgregarAvanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActividadAgregarAvanceActionPerformed
        ((CardLayout)paneActividadesBase.getLayout()).show(paneActividadesBase, "agregarAvance");
        txtAvanceDescripcion.setText("");
        cmbAvanceTipo.setSelectedIndex(-1);
        spnAvanceHoras.setValue(0);
    }//GEN-LAST:event_btnActividadAgregarAvanceActionPerformed

    private void lstActividadAvancesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstActividadAvancesMouseClicked
        /*JList list = (JList) evt.getSource();
        if(evt.getClickCount()==2){
            int index=list.locationToIndex(evt.getPoint());
            Actividad act = (Actividad)actividadesListModel.get(index);
            txtActividadId.setText(act.getIdTarea());
            txtActividadNombre.setText(act.getNombreTarea());
            txtActividadIdUsuario.setText(act.getIdUsuario());
            txtActividadFechaCreacion.setText(safeParseToString(act.getFechaCreacion()));
            txtActividadFechaCompletado.setText(safeParseToString(act.getFechaCompletado()));
            txtActividadFechaInicio.setText(safeParseToString(act.getFechaInicio()));
            txtActividadFechaFin.setText(safeParseToString(act.getFechaFin()));
            txtActividadNotas.setText(act.getNota());
            txtActividadEtiquetas.setText(act.getEtiqueta());
            txtActividadPadre.setText(act.getTareaPadre());
            
            txtActividadAvances.setText("Fix me");
            ((CardLayout)paneActividadesBase.getLayout()).show(paneActividadesBase, "actividad");

        }*/
    }//GEN-LAST:event_lstActividadAvancesMouseClicked

    private void btnAgregarAvanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAvanceActionPerformed
        Date Fecha = new Date();
        java.sql.Date FechaMod = sqlDate(Fecha);
        Ctrl.getDTOAvance().getUnAvance().setIdActividad(current_actividad.getIdActividad());
        Ctrl.getDTOAvance().getUnAvance().setFechaAvance(FechaMod);
        Ctrl.getDTOAvance().getUnAvance().setHorasDedicadas((Integer) spnAvanceHoras.getValue());
        Ctrl.getDTOAvance().getUnAvance().setTipoAvance(cmbAvanceTipo.getSelectedIndex()+1);
        Ctrl.getDTOAvance().getUnAvance().setIdUsuario(current_user.getIdUsuario());
        Ctrl.getDTOAvance().getUnAvance().setDescripcion(txtAvanceDescripcion.getText());
        
        Ctrl.CrearAvance();
        ((CardLayout)paneActividadesBase.getLayout()).show(paneActividadesBase, "actividad");
        fillAvancesList();
    }//GEN-LAST:event_btnAgregarAvanceActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ((CardLayout)paneActividadesBase.getLayout()).show(paneActividadesBase, "actividad");
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActividadAgregarAvance;
    private javax.swing.JButton btnActividadIrAtras;
    private javax.swing.JButton btnAgregarAvance;
    private javax.swing.JButton btnImportarImportar;
    private javax.swing.JButton btnImportarSeleccionar;
    private javax.swing.JComboBox<String> cmbAvanceTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane lstActividadActividades;
    private javax.swing.JList<String> lstActividadAvances;
    private javax.swing.JList<String> lstActividades;
    private javax.swing.JPanel paneActividadesActividad;
    private javax.swing.JPanel paneActividadesAgregarAvance;
    private javax.swing.JPanel paneActividadesBase;
    private javax.swing.JPanel paneActividadesLista;
    private javax.swing.JPanel paneImportar;
    private javax.swing.JPasswordField pwdPerfilContra1;
    private javax.swing.JPasswordField pwdPerfilContra2;
    private javax.swing.JSpinner spnAvanceHoras;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JLabel txtActividadAvances;
    private javax.swing.JLabel txtActividadEtiquetas;
    private javax.swing.JLabel txtActividadFechaCompletado;
    private javax.swing.JLabel txtActividadFechaCreacion;
    private javax.swing.JLabel txtActividadFechaFin;
    private javax.swing.JLabel txtActividadFechaInicio;
    private javax.swing.JLabel txtActividadId;
    private javax.swing.JLabel txtActividadIdUsuario;
    private javax.swing.JLabel txtActividadNombre;
    private javax.swing.JLabel txtActividadNotas;
    private javax.swing.JLabel txtActividadPadre;
    private javax.swing.JTextArea txtAvanceDescripcion;
    private javax.swing.JTextField txtImportarPath;
    private javax.swing.JTextField txtPerfilCorreo;
    private javax.swing.JTextField txtPerfilUsuario;
    // End of variables declaration//GEN-END:variables

    private void fillActivitiesList() {
        actividadesListModel.clear();
        try {
            if(current_user.getRolUsuario()==1)
                actividadesListModel.addAll(Ctrl.ConsultarActividades());
            else
                actividadesListModel.addAll(Ctrl.ConsultarActividades(current_user.getIdUsuario()));
        } catch (SQLException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private int fillAvancesList() {
        avancesListModel.clear();
        try {
            ArrayList<Model.Avance> avances = Ctrl.ConsultarAvancesActividad(current_actividad.getIdActividad());
            avancesListModel.addAll(avances);
            return avances.size();
        } catch (SQLException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            return -1;
        }
    }
}
